/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentExample: typeof import('./.vitepress/theme/components/ContentExample.vue')['default']
    ContentExamples: typeof import('./.vitepress/theme/components/ContentExamples.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
  }
}
